### ISSUE TITLE
Contribution policy and vision

### ISSUE THREAD

**Issue by zerho** [4face-studi0/Covid19#7]
Hi @4face-studi0 
the project might be interesting, but you might explain in the README what do you expect from a contributor joining or at least what goal you'd like to reach se that people can understand if they're interested in joining.
There is really not enough right now in order to trigger someone's interest ✌🏻.

**Comment by 4face-studi0** [comment]
Yes, I know, you're absolutely right 🙂 I will improve the readme ASAP.
Thank you

**Comment by 4face-studi0** [comment]
@zerho related PR #8
